package com.ncu.library.userservice.irepository;

import java.util.List;
import com.ncu.library.userservice.model.User;

public interface iUserRepository {

    // Fetch all users
    List<User> getAllUsers();

    // Fetch all users by location (updated)
    List<User> getUsersByLocation(String userLocation);

    // Fetch user by id
    User getUserById(Integer id);

    // Add new user (Id will be auto-generated by DB)
    User addUser(User user);
}
