package com.ncu.library.userservice.dto;

public class UserDto {

    private Integer id;          // Auto-generated by DB
    private String userName;     // Manually filled
    private String userLocation; // Manually filled

    public UserDto() {
    }

    public UserDto(Integer id, String userName, String userLocation) {
        this.id = id;
        this.userName = userName;
        this.userLocation = userLocation;
    }

    // Getters and Setters
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserLocation() {
        return userLocation;
    }

    public void setUserLocation(String userLocation) {
        this.userLocation = userLocation;
    }
}
